// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalcRequest.proto

package com.shiyanlou.bean;

public final class CalcRequestProto {
  private CalcRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CalcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CalcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 num1 = 1;</code>
     */
    int getNum1();

    /**
     * <code>int32 num2 = 2;</code>
     */
    int getNum2();

    /**
     * <code>string symbol = 3;</code>
     */
    java.lang.String getSymbol();
    /**
     * <code>string symbol = 3;</code>
     */
    com.google.protobuf.ByteString
        getSymbolBytes();
  }
  /**
   * Protobuf type {@code CalcRequest}
   */
  public  static final class CalcRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CalcRequest)
      CalcRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CalcRequest.newBuilder() to construct.
    private CalcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CalcRequest() {
      num1_ = 0;
      num2_ = 0;
      symbol_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CalcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              num1_ = input.readInt32();
              break;
            }
            case 16: {

              num2_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              symbol_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shiyanlou.bean.CalcRequestProto.internal_static_CalcRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shiyanlou.bean.CalcRequestProto.internal_static_CalcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shiyanlou.bean.CalcRequestProto.CalcRequest.class, com.shiyanlou.bean.CalcRequestProto.CalcRequest.Builder.class);
    }

    public static final int NUM1_FIELD_NUMBER = 1;
    private int num1_;
    /**
     * <code>int32 num1 = 1;</code>
     */
    @Override
    public int getNum1() {
      return num1_;
    }

    public static final int NUM2_FIELD_NUMBER = 2;
    private int num2_;
    /**
     * <code>int32 num2 = 2;</code>
     */
    @Override
    public int getNum2() {
      return num2_;
    }

    public static final int SYMBOL_FIELD_NUMBER = 3;
    private volatile java.lang.Object symbol_;
    /**
     * <code>string symbol = 3;</code>
     */
    @Override
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      }
    }
    /**
     * <code>string symbol = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) {
        return false;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (num1_ != 0) {
        output.writeInt32(1, num1_);
      }
      if (num2_ != 0) {
        output.writeInt32(2, num2_);
      }
      if (!getSymbolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, symbol_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
        return size;
      }

      size = 0;
      if (num1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, num1_);
      }
      if (num2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, num2_);
      }
      if (!getSymbolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, symbol_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.shiyanlou.bean.CalcRequestProto.CalcRequest)) {
        return super.equals(obj);
      }
      com.shiyanlou.bean.CalcRequestProto.CalcRequest other = (com.shiyanlou.bean.CalcRequestProto.CalcRequest) obj;

      boolean result = true;
      result = result && (getNum1()
          == other.getNum1());
      result = result && (getNum2()
          == other.getNum2());
      result = result && getSymbol()
          .equals(other.getSymbol());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUM1_FIELD_NUMBER;
      hash = (53 * hash) + getNum1();
      hash = (37 * hash) + NUM2_FIELD_NUMBER;
      hash = (53 * hash) + getNum2();
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.shiyanlou.bean.CalcRequestProto.CalcRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shiyanlou.bean.CalcRequestProto.CalcRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shiyanlou.bean.CalcRequestProto.CalcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shiyanlou.bean.CalcRequestProto.CalcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shiyanlou.bean.CalcRequestProto.CalcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shiyanlou.bean.CalcRequestProto.CalcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shiyanlou.bean.CalcRequestProto.CalcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.shiyanlou.bean.CalcRequestProto.CalcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.shiyanlou.bean.CalcRequestProto.CalcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.shiyanlou.bean.CalcRequestProto.CalcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.shiyanlou.bean.CalcRequestProto.CalcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.shiyanlou.bean.CalcRequestProto.CalcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.shiyanlou.bean.CalcRequestProto.CalcRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CalcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CalcRequest)
        com.shiyanlou.bean.CalcRequestProto.CalcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.shiyanlou.bean.CalcRequestProto.internal_static_CalcRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shiyanlou.bean.CalcRequestProto.internal_static_CalcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shiyanlou.bean.CalcRequestProto.CalcRequest.class, com.shiyanlou.bean.CalcRequestProto.CalcRequest.Builder.class);
      }

      // Construct using com.shiyanlou.bean.CalcRequestProto.CalcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        num1_ = 0;

        num2_ = 0;

        symbol_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.shiyanlou.bean.CalcRequestProto.internal_static_CalcRequest_descriptor;
      }

      @java.lang.Override
      public com.shiyanlou.bean.CalcRequestProto.CalcRequest getDefaultInstanceForType() {
        return com.shiyanlou.bean.CalcRequestProto.CalcRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.shiyanlou.bean.CalcRequestProto.CalcRequest build() {
        com.shiyanlou.bean.CalcRequestProto.CalcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.shiyanlou.bean.CalcRequestProto.CalcRequest buildPartial() {
        com.shiyanlou.bean.CalcRequestProto.CalcRequest result = new com.shiyanlou.bean.CalcRequestProto.CalcRequest(this);
        result.num1_ = num1_;
        result.num2_ = num2_;
        result.symbol_ = symbol_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shiyanlou.bean.CalcRequestProto.CalcRequest) {
          return mergeFrom((com.shiyanlou.bean.CalcRequestProto.CalcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.shiyanlou.bean.CalcRequestProto.CalcRequest other) {
        if (other == com.shiyanlou.bean.CalcRequestProto.CalcRequest.getDefaultInstance()) {
          return this;
        }
        if (other.getNum1() != 0) {
          setNum1(other.getNum1());
        }
        if (other.getNum2() != 0) {
          setNum2(other.getNum2());
        }
        if (!other.getSymbol().isEmpty()) {
          symbol_ = other.symbol_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shiyanlou.bean.CalcRequestProto.CalcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.shiyanlou.bean.CalcRequestProto.CalcRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int num1_ ;
      /**
       * <code>int32 num1 = 1;</code>
       */
      @Override
      public int getNum1() {
        return num1_;
      }
      /**
       * <code>int32 num1 = 1;</code>
       */
      public Builder setNum1(int value) {
        
        num1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 num1 = 1;</code>
       */
      public Builder clearNum1() {
        
        num1_ = 0;
        onChanged();
        return this;
      }

      private int num2_ ;
      /**
       * <code>int32 num2 = 2;</code>
       */
      @Override
      public int getNum2() {
        return num2_;
      }
      /**
       * <code>int32 num2 = 2;</code>
       */
      public Builder setNum2(int value) {
        
        num2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 num2 = 2;</code>
       */
      public Builder clearNum2() {
        
        num2_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object symbol_ = "";
      /**
       * <code>string symbol = 3;</code>
       */
      @Override
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string symbol = 3;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string symbol = 3;</code>
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        symbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 3;</code>
       */
      public Builder clearSymbol() {
        
        symbol_ = getDefaultInstance().getSymbol();
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 3;</code>
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        symbol_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CalcRequest)
    }

    // @@protoc_insertion_point(class_scope:CalcRequest)
    private static final com.shiyanlou.bean.CalcRequestProto.CalcRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.shiyanlou.bean.CalcRequestProto.CalcRequest();
    }

    public static com.shiyanlou.bean.CalcRequestProto.CalcRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CalcRequest>
        PARSER = new com.google.protobuf.AbstractParser<CalcRequest>() {
      @java.lang.Override
      public CalcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalcRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CalcRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CalcRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.shiyanlou.bean.CalcRequestProto.CalcRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalcRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CalcRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CalcRequest.proto\"9\n\013CalcRequest\022\014\n\004nu" +
      "m1\030\001 \001(\005\022\014\n\004num2\030\002 \001(\005\022\016\n\006symbol\030\003 \001(\tB&" +
      "\n\022com.shiyanlou.beanB\020CalcRequestProtob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          @Override
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CalcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CalcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CalcRequest_descriptor,
        new java.lang.String[] { "Num1", "Num2", "Symbol", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
